using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RazorPay.Partner.Services;
using System.Net;
using System.Net.Http.Headers;
using static System.Net.WebRequestMethods;

namespace WebApplication3.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class FileUploadController : ControllerBase
    {
        RazorPayPartnerClient razorPayPartnerClient = new RazorPayPartnerClient();
        [HttpPost("upload")]
        public async Task<IActionResult> upload(IFormFile file)
        {
            try
            {

                //var filePath = Path.GetTempFileName();

                //using (var stream = System.IO.File.Create(filePath))
                //{
                //    // The formFile is the method parameter which type is IFormFile
                //    // Saves the files to the local file system using a file name generated by the app.
                //    await file.CopyToAsync(stream);
                //}

                ////string header = string.Format("--{0}\r\nContent-Disposition: form-data; name=\"{1}\"; filename=\"{2}\"\r\nContent-Type: {3}\r\n\r\n",
                ////    file.FileName ?? 
                ////    file.ContentType ?? "application/octet-stream");

                ////formDataStream.Write(encoding.GetBytes(header), 0, encoding.GetByteCount(header));
                ////// Write the file data directly to the Stream, rather than serializing it to a string.
                ////formDataStream.Write(fileToUpload.File, 0, fileToUpload.File.Length);

                ////var result = await razorPayPartnerClient.CallApi<object>($"accounts/acc_Jrx7OzwJXge4YO/documents", new
                ////{
                ////    file = filePath,
                ////    document_type = "gst_certificate"
                ////});

                var formContent = new FormUrlEncodedContent(new[]
                {
                    new KeyValuePair<string, string>("file", "https://oxydebug.sgp1.cdn.digitaloceanspaces.com/Rent/Apartments/2021%E2%80%99-%E2%80%9809%E2%80%99-%E2%80%9822%E2%80%99T%E2%80%9907%E2%80%99:%E2%80%9908%E2%80%99:%E2%80%9919.6758602+00:00Sophie%20Sollmann%20%202016-11-03%2006-13-55%20jpg"),
                    new KeyValuePair<string, string>("document_type", "business_proof_url")
                });
                ////var result = await razorPayPartnerClient.Http.PostAsync("accounts/acc_Jrx7OzwJXge4YO/documents", formContent);
                var multipartFormContent = new MultipartFormDataContent();
                //var fileStreamContent = new StreamContent(System.IO.File.OpenRead(filePath));
                //fileStreamContent.Headers.ContentType = new MediaTypeHeaderValue("image/png");

                ////Add the file
                //multipartFormContent.Add();
                //HttpContent cont = 
                HttpWebRequest req = new HttpWebRequest()
                var result = await razorPayPartnerClient.Http.PostAsync("accounts/acc_Jrx7OzwJXge4YO/documents", formContent);
            }
            catch (Exception ex)
            {

            }
            return Ok(file);
        }
    }
}